easy_admin:
    site_name: '<h2>DO GREEN YOURSELF - <em>Backend</em></h2>'

    formats:
        date: 'd/m/Y'
        datetime: 'd/m/Y H:i'

    list:
        max_results: 10
        collapse_actions: true
        actions: ['show', 'edit','delete']
        batch_actions: ['delete']


